/**
 * Emits `src/components/site/gallery.generated.tsx`: every registry item
 * resolved to the component that draws it, with no prop but `size`, so its own
 * default behavior runs.
 *
 * This is what makes a new component appear on the landing page and in the docs
 * without anyone editing an unrelated file. Notes: `docs/gallery-coverage.md`.
 */

import { readFile, writeFile } from "node:fs/promises"

import { resolveGallery } from "./lib/gallery.mjs"

const registry = JSON.parse(await readFile("registry.json", "utf8"))
const resolved = await resolveGallery(registry)

// One import per component, not per item: a dozen Foundations items share the
// handful of machines that exercise them.
const modules = [...new Set(resolved.filter((e) => !e.webgl).map((e) => e.module))]
const named = new Map()
for (const entry of resolved) {
  if (!entry.webgl) named.set(entry.module, entry.export)
}

const lines = [
  `"use client"`,
  "",
  "/**",
  " * GENERATED by `scripts/build-gallery.mjs` — do not edit.",
  " *",
  " * Every registry item, mapped to the component that draws it. The gallery",
  " * falls back to this when no hand-posed card or demo exists, so a component",
  " * added to the registry is never invisible. Notes: `docs/gallery-coverage.md`.",
  " */",
  "",
  `import type * as React from "react"`,
  "",
  `import type { RobotSize, RobotVariant } from "@/lib/robocn/style"`,
  "",
  ...modules.map((module) => `import { ${named.get(module)} } from "${module}"`),
  "",
  "/** All a fallback card or demo needs to set. Everything else is the",
  " *  component's own default, which is the pose and the cycle its author wrote. */",
  "export interface GalleryProps {",
  "  size?: RobotSize | number",
  "  variant?: RobotVariant",
  "}",
  "",
  "export interface GalleryEntry {",
  "  /** Registry item name, which is also the doc slug. */",
  "  item: string",
  "  /** The item whose component is drawn — itself, or the machine it solves. */",
  "  draws: string",
  "  /** A solver draws its machine as a drawing rather than a product shot. */",
  "  blueprint: boolean",
  "  /** Needs a WebGL context, so the grid lazy-loads it instead. */",
  "  webgl: boolean",
  "  component: React.ComponentType<GalleryProps> | null",
  "}",
  "",
  "export const galleryEntries: Record<string, GalleryEntry> = {",
  ...resolved.map(
    (entry) =>
      `  ${JSON.stringify(entry.item)}: { item: ${JSON.stringify(entry.item)}, ` +
      `draws: ${JSON.stringify(entry.draws)}, blueprint: ${entry.blueprint}, ` +
      `webgl: ${entry.webgl}, component: ${entry.webgl ? "null" : entry.export} },`,
  ),
  "}",
  "",
]

await writeFile("src/components/site/gallery.generated.tsx", lines.join("\n"))
console.log(`Gallery map prepared: ${resolved.length} registry items.`)
